name: Release

on:
  push:
    tags:
      - "*"

jobs:
  pod-trunk-push:
    runs-on: macOS-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.2"
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push Brightroom.podspec --allow-warnings
